vim.wo.number = true -- Make line numbers (default: false)
vim.wo.relativenumber = true -- Turns Relative line numbers on
vim.o.clipboard = 'unnamedplus' -- Sync clipboard between OS and nvim (default: '')
vim.o.wrap = true -- Display lines as one long line (default: true)
vim.o.linebreak = true -- Companion to wrap, don't split words (default: false)
vim.o.mouse = 'a' -- Enable mouse mode (default: '')
vim.o.autoindent = true -- Copy indent from current line when starting a new one (default: true)
vim.o.ignorecase = true -- Case-insensitive searching unless \C or capital in search (default: false)
vim.o.smartcase = true -- Smart case (default: false)
vim.o.hlsearch = true -- Set highlight on search
vim.o.breakindent = true -- Enable break indent
vim.o.undofile = true -- Save undo history
vim.wo.signcolumn = 'yes' -- Kepp signcolumn on by default
vim.o.backup = false -- Creates a backup file
vim.o.writebackup = false -- Creates a backupfile during the write of the file
vim.o.completeopt = 'menuone,noinsert,noselect,preview' -- Creates a completition window
vim.opt.termguicolors = true -- Set term gui colors to enable highlight groups
vim.o.whichwrap = '<>hl' -- Wich keys are allowed to travel to next/prev line
vim.o.scrolloff = 4 -- Minimal number of screen lines to keep above and below the cursor
vim.o.shiftwidth = 4 -- Number of spaces inserted for each identation
vim.o.tabstop = 4 -- Insert n spaces for tab
vim.o.softtabstop = 4 -- Number of spaces that a tab counts for while performing editing operations
vim.o.expandtab = true -- convert tabs to spaces
vim.o.cursorline = true -- highlight the current line
vim.o.splitbelow = true -- force all horizontal splits to go below current window
vim.o.splitright = true -- force all vertical splits to go to the right of the current window
vim.o.swapfile = true -- creates a swap file to use if the power cuts
vim.o.smartindent = true -- make identing smarter depending on brackets or parentesis
vim.o.showmode = true -- show mode like INSERT VISUAL and that stuff
vim.o.showtabline = 1 -- show tab line only if there are 2 or more tabs open
vim.o.backspace = 'indent,eol,start' -- allow backspace on
vim.o.pumheight = 7 -- pop up menu height
vim.o.fileencoding = 'utf-8' -- the encoding written to a file
vim.o.cmdheight = 1 -- lines of the command prompt in vim
vim.opt.conceallevel = 2
